[2023-07-26T10:24:14.554+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgresv01.get_s3_id scheduled__2023-07-25T00:00:00+00:00 [queued]>
[2023-07-26T10:24:14.559+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgresv01.get_s3_id scheduled__2023-07-25T00:00:00+00:00 [queued]>
[2023-07-26T10:24:14.560+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-07-26T10:24:14.568+0000] {taskinstance.py:1327} INFO - Executing <Task(S3KeySensor): get_s3_id> on 2023-07-25 00:00:00+00:00
[2023-07-26T10:24:14.571+0000] {standard_task_runner.py:57} INFO - Started process 181 to run task
[2023-07-26T10:24:14.574+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgresv01', 'get_s3_id', 'scheduled__2023-07-25T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_dependency.py', '--cfg-path', '/tmp/tmpebg72j5c']
[2023-07-26T10:24:14.576+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask get_s3_id
[2023-07-26T10:24:14.613+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_postgresv01.get_s3_id scheduled__2023-07-25T00:00:00+00:00 [running]> on host 046143d89825
[2023-07-26T10:24:14.674+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='richy' AIRFLOW_CTX_DAG_ID='dag_with_postgresv01' AIRFLOW_CTX_TASK_ID='get_s3_id' AIRFLOW_CTX_EXECUTION_DATE='2023-07-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-25T00:00:00+00:00'
[2023-07-26T10:24:14.675+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucket/iris-dataset.csv
[2023-07-26T10:24:14.683+0000] {base.py:73} INFO - Using connection ID 'aws_conn' for task execution.
[2023-07-26T10:24:14.684+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_conn', conn_type='aws') credentials retrieved from extra.
[2023-07-26T10:24:14.963+0000] {base.py:255} INFO - Success criteria met. Exiting.
[2023-07-26T10:24:14.971+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=dag_with_postgresv01, task_id=get_s3_id, execution_date=20230725T000000, start_date=20230726T102414, end_date=20230726T102414
[2023-07-26T10:24:15.038+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-26T10:24:15.052+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-26T14:28:33.364+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgresv01.get_s3_id scheduled__2023-07-25T00:00:00+00:00 [queued]>
[2023-07-26T14:28:33.371+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgresv01.get_s3_id scheduled__2023-07-25T00:00:00+00:00 [queued]>
[2023-07-26T14:28:33.372+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-07-26T14:28:33.381+0000] {taskinstance.py:1327} INFO - Executing <Task(S3KeySensor): get_s3_id> on 2023-07-25 00:00:00+00:00
[2023-07-26T14:28:33.385+0000] {standard_task_runner.py:57} INFO - Started process 1527 to run task
[2023-07-26T14:28:33.388+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgresv01', 'get_s3_id', 'scheduled__2023-07-25T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_dependency.py', '--cfg-path', '/tmp/tmpqjwdhh9c']
[2023-07-26T14:28:33.390+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask get_s3_id
[2023-07-26T14:28:33.431+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_postgresv01.get_s3_id scheduled__2023-07-25T00:00:00+00:00 [running]> on host 93edf6c77c0f
[2023-07-26T14:28:33.495+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='richy' AIRFLOW_CTX_DAG_ID='dag_with_postgresv01' AIRFLOW_CTX_TASK_ID='get_s3_id' AIRFLOW_CTX_EXECUTION_DATE='2023-07-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-25T00:00:00+00:00'
[2023-07-26T14:28:33.496+0000] {s3.py:99} INFO - Poking for key : s3://minikubebucket/iris-dataset.csv
[2023-07-26T14:28:33.504+0000] {base_aws.py:551} WARNING - Unable to find AWS Connection ID 'aws_conn', switching to empty.
[2023-07-26T14:28:33.505+0000] {base_aws.py:160} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2023-07-26T14:28:35.844+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 225, in execute
    raise e
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 212, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 130, in poke
    return self._check_key(self.bucket_key)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 118, in _check_key
    obj = self.hook.head_object(key, bucket_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 115, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 86, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 503, in head_object
    return self.get_conn().head_object(Bucket=bucket_name, Key=key)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 948, in _make_api_call
    operation_model, request_dict, request_context
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 970, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 137, in create_request
    operation_name=operation_model.name,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/signers.py", line 189, in sign
    auth.add_auth(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2023-07-26T14:28:35.853+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgresv01, task_id=get_s3_id, execution_date=20230725T000000, start_date=20230726T142833, end_date=20230726T142835
[2023-07-26T14:28:35.861+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 3 for task get_s3_id (Unable to locate credentials; 1527)
[2023-07-26T14:28:35.920+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-26T14:28:35.935+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
