[2023-07-26T14:58:39.353+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgresv02.get_s3_id manual__2023-07-26T14:58:38.566240+00:00 [queued]>
[2023-07-26T14:58:39.360+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgresv02.get_s3_id manual__2023-07-26T14:58:38.566240+00:00 [queued]>
[2023-07-26T14:58:39.361+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-07-26T14:58:39.369+0000] {taskinstance.py:1327} INFO - Executing <Task(S3KeySensor): get_s3_id> on 2023-07-26 14:58:38.566240+00:00
[2023-07-26T14:58:39.372+0000] {standard_task_runner.py:57} INFO - Started process 2856 to run task
[2023-07-26T14:58:39.375+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgresv02', 'get_s3_id', 'manual__2023-07-26T14:58:38.566240+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_dependency.py', '--cfg-path', '/tmp/tmp0mgz9qq9']
[2023-07-26T14:58:39.377+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask get_s3_id
[2023-07-26T14:58:39.416+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_postgresv02.get_s3_id manual__2023-07-26T14:58:38.566240+00:00 [running]> on host 93edf6c77c0f
[2023-07-26T14:58:39.472+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='richy' AIRFLOW_CTX_DAG_ID='dag_with_postgresv02' AIRFLOW_CTX_TASK_ID='get_s3_id' AIRFLOW_CTX_EXECUTION_DATE='2023-07-26T14:58:38.566240+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-26T14:58:38.566240+00:00'
[2023-07-26T14:58:39.475+0000] {s3.py:99} INFO - Poking for key : s3://backendbucket/iris-dataset.csv
[2023-07-26T14:58:39.484+0000] {base.py:73} INFO - Using connection ID 'aws_conn' for task execution.
[2023-07-26T14:58:39.485+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_conn', conn_type='aws') credentials retrieved from extra.
[2023-07-26T14:58:44.751+0000] {s3.py:99} INFO - Poking for key : s3://backendbucket/iris-dataset.csv
[2023-07-26T14:58:49.775+0000] {s3.py:99} INFO - Poking for key : s3://backendbucket/iris-dataset.csv
[2023-07-26T14:58:54.797+0000] {s3.py:99} INFO - Poking for key : s3://backendbucket/iris-dataset.csv
[2023-07-26T14:58:59.818+0000] {s3.py:99} INFO - Poking for key : s3://backendbucket/iris-dataset.csv
[2023-07-26T14:59:04.863+0000] {s3.py:99} INFO - Poking for key : s3://backendbucket/iris-dataset.csv
[2023-07-26T14:59:09.885+0000] {s3.py:99} INFO - Poking for key : s3://backendbucket/iris-dataset.csv
[2023-07-26T14:59:09.890+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 242, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 30.41460330600239 seconds exceeds the specified timeout of 30.
[2023-07-26T14:59:09.899+0000] {taskinstance.py:1350} INFO - Immediate failure requested. Marking task as FAILED. dag_id=dag_with_postgresv02, task_id=get_s3_id, execution_date=20230726T145838, start_date=20230726T145839, end_date=20230726T145909
[2023-07-26T14:59:09.907+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 9 for task get_s3_id (Sensor has timed out; run duration of 30.41460330600239 seconds exceeds the specified timeout of 30.; 2856)
[2023-07-26T14:59:09.959+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-26T14:59:09.978+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
