[2023-07-26T14:57:01.738+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgresv02.get_s3_id scheduled__2023-07-25T00:00:00+00:00 [queued]>
[2023-07-26T14:57:01.744+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgresv02.get_s3_id scheduled__2023-07-25T00:00:00+00:00 [queued]>
[2023-07-26T14:57:01.744+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-07-26T14:57:01.752+0000] {taskinstance.py:1327} INFO - Executing <Task(S3KeySensor): get_s3_id> on 2023-07-25 00:00:00+00:00
[2023-07-26T14:57:01.756+0000] {standard_task_runner.py:57} INFO - Started process 2787 to run task
[2023-07-26T14:57:01.759+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgresv02', 'get_s3_id', 'scheduled__2023-07-25T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_dependency.py', '--cfg-path', '/tmp/tmpmwuvufbq']
[2023-07-26T14:57:01.761+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask get_s3_id
[2023-07-26T14:57:01.801+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_with_postgresv02.get_s3_id scheduled__2023-07-25T00:00:00+00:00 [running]> on host 93edf6c77c0f
[2023-07-26T14:57:01.855+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='richy' AIRFLOW_CTX_DAG_ID='dag_with_postgresv02' AIRFLOW_CTX_TASK_ID='get_s3_id' AIRFLOW_CTX_EXECUTION_DATE='2023-07-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-25T00:00:00+00:00'
[2023-07-26T14:57:01.856+0000] {s3.py:99} INFO - Poking for key : s3://backendbucket/iris-dataset.csv
[2023-07-26T14:57:01.865+0000] {base.py:73} INFO - Using connection ID 'aws_conn' for task execution.
[2023-07-26T14:57:01.866+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='aws_conn', conn_type='aws') credentials retrieved from extra.
[2023-07-26T14:57:07.140+0000] {s3.py:99} INFO - Poking for key : s3://backendbucket/iris-dataset.csv
[2023-07-26T14:57:12.169+0000] {s3.py:99} INFO - Poking for key : s3://backendbucket/iris-dataset.csv
[2023-07-26T14:57:17.191+0000] {s3.py:99} INFO - Poking for key : s3://backendbucket/iris-dataset.csv
[2023-07-26T14:57:22.216+0000] {s3.py:99} INFO - Poking for key : s3://backendbucket/iris-dataset.csv
[2023-07-26T14:57:27.243+0000] {s3.py:99} INFO - Poking for key : s3://backendbucket/iris-dataset.csv
[2023-07-26T14:57:32.272+0000] {s3.py:99} INFO - Poking for key : s3://backendbucket/iris-dataset.csv
[2023-07-26T14:57:32.288+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 242, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 30.431974764000188 seconds exceeds the specified timeout of 30.
[2023-07-26T14:57:32.311+0000] {taskinstance.py:1350} INFO - Immediate failure requested. Marking task as FAILED. dag_id=dag_with_postgresv02, task_id=get_s3_id, execution_date=20230725T000000, start_date=20230726T145701, end_date=20230726T145732
[2023-07-26T14:57:32.327+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 8 for task get_s3_id (Sensor has timed out; run duration of 30.431974764000188 seconds exceeds the specified timeout of 30.; 2787)
[2023-07-26T14:57:32.380+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-26T14:57:32.398+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
